### ISSUE TITLE
IDs not found or incorrectly renamed

### ISSUE THREAD

**Issue by reneruiz** [niemasd/MemCard-PRO-Renamer#1]
I tried to run the script against my saves:

```
D43E0100
G4BE0800
G4ME6900
G4SE0100
GAFE0100
GALE0102
GEDE0100
GFZE0100
GGSEA400
GIKE7000
GM4E0100
GM8E0102
GMPE0101
GMSE0100
GSAE0101
GSWE6400
GZLE0100
```

Appears that `GSWE6400` is the only one ID-ed but it was ID-ed as `HARRY POTTER OCH DEN FLAMMANDE BÄGAREN`. (Sidenote: Could we get title case format instead of all caps?)

But it should actually be `Star Wars Rogue Squadron II: Rogue Leader`.

![CleanShot 2024-01-16 at 21 55 53](https://github.com/niemasd/GameDB-GC/assets/394085/008173a2-f88a-4c50-a6b0-8d510379e495)

I found another potential [source](https://www.gametdb.com/Wii/Downloads) for GameIDs, however the format doesn't quite line up nicely.

```
Title: Star Wars Rogue Squadron II: Rogue Leader
MemCardPro ID: GSWE6400
GameTDB ID: GSWE64
```

Here's the MCP mapping for all my saves with title + ID:

![CleanShot 2024-01-16 at 22 04 17](https://github.com/niemasd/GameDB-GC/assets/394085/147cf8a7-4c94-434d-9734-bfe47a6e74ee)

**Comment by niemasd** [comment]
Thanks for reposting here, and sorry again for missing your GitHub Issue in the other repo! Would you mind sharing a couple of the saves with me (e.g. as a zip attached in a reply) so I can play around with it and test it out?

**Comment by niemasd** [comment]
Actually, I was able to make a test by just putting dummy files in folders named according to your list, and it seems to have worked! It was a really silly bug LOL. Can you try it now and let me know if it works?

Regarding the titles, I can absolutely update that in the future! That's part of GameDB (the `title.txt` files), so I can bulk fix them some time soon. I'll probably knock that out tonight or tomorrow or so. Will follow up when I do

https://github.com/niemasd/GameDB-GC/issues/3

**Comment by reneruiz** [comment]
That worked great!

![CleanShot 2024-06-20 at 20 49 53](https://github.com/niemasd/MemCard-PRO-Renamer/assets/394085/6e6add44-86b7-4397-be7c-a35c44ea9e52)

Thanks for this and also considering the title casing change for the future! 🙏

**Comment by niemasd** [comment]
No problem! I just released a new version that should fix the title casing issue as well. Can you try the newest version and let me know?

**Comment by reneruiz** [comment]
Yes that's a lot more readable!

![CleanShot 2024-06-20 at 23 14 06](https://github.com/niemasd/MemCard-PRO-Renamer/assets/394085/1e0e5d16-234a-4fcd-9606-35a1808b0ce9)

Stylistic suggestion but would it make more sense to just strip out the `:` character altogether rather than replacing it with an `_`? I'm not sure it works as a 1:1 replacement. But just my 2 cents!

```
Mario Kart Double Dash!!
Metal Gear Solid The Twin Snakes
```

EDIT: Alternative suggestion, and you can replace it with a `-` and a preceding space character, since there's usually a space character that follows a `:`.  

```
Mario Kart - Double Dash!!
Metal Gear Solid - The Twin Snakes
```

**Comment by niemasd** [comment]
Awesome, thanks for confirming! And yeah, that's a good idea; I'll try it out right now. I still need to strip *some* characters to `_` (or some other placeholder), e.g. if there happen to be other strange characters in some titles in GameDB-GC, but your idea of replacing `:` with ` -` should work for most cases. I'll follow up in a sec

**Comment by niemasd** [comment]
Okay, I just pushed a new version that replaces `:` with ` -`; can you try now?

**Comment by reneruiz** [comment]
Wow that was fast! This looks fantastic, thank you so much!

![CleanShot 2024-06-20 at 23 30 16](https://github.com/niemasd/MemCard-PRO-Renamer/assets/394085/ca95f110-3fd2-4144-b539-0d5b53c6c9f5)

**Comment by niemasd** [comment]
No problem! Thank you for catching the bug + testing the fix, as well as for the great suggestions 😄
